# @file publish-binaries.yml
#
# A workflow for publishing platform binaries for the readiness tool.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish Binaries

    runs-on: windows-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: ‚úÖ Checkout Repository ‚úÖ
        uses: actions/checkout@v5

      - name: üõ†Ô∏è Download Rust Tools üõ†Ô∏è
        uses: OpenDevicePartnership/patina-devops/.github/actions/rust-tool-cache@v0.0.4

      - name: Build Platform Binaries
        run: cargo make build

      - name: Collect Binaries
        run: |
          # Create a directory for the release artifacts
          mkdir -p "artifacts/intel"
          mkdir -p "artifacts/qemu"
          mkdir -p "artifacts/shell_app"

          # Copy the binaries to the artifacts directory
          cp target/x86_64-unknown-uefi/debug/intel_dxe_readiness_capture.efi artifacts/intel/intel_dxe_readiness_capture.efi
          cp target/x86_64-unknown-uefi/debug/intel_dxe_readiness_capture.pdb artifacts/intel/intel_dxe_readiness_capture.pdb
          cp target/x86_64-unknown-uefi/debug/intel_lnl_dxe_readiness_capture.efi artifacts/intel/intel_lnl_dxe_readiness_capture.efi
          cp target/x86_64-unknown-uefi/debug/intel_lnl_dxe_readiness_capture.pdb artifacts/intel/intel_lnl_dxe_readiness_capture.pdb
          cp target/x86_64-unknown-uefi/debug/qemu_dxe_readiness_capture.efi artifacts/qemu/qemu_dxe_readiness_capture.efi
          cp target/x86_64-unknown-uefi/debug/qemu_dxe_readiness_capture.pdb artifacts/qemu/qemu_dxe_readiness_capture.pdb
          cp target/x86_64-unknown-uefi/debug/uefishell_dxe_readiness_capture.efi artifacts/shell_app/uefishell_dxe_readiness_capture.efi
          cp target/x86_64-unknown-uefi/debug/uefishell_dxe_readiness_capture.pdb artifacts/shell_app/uefishell_dxe_readiness_capture.pdb

      - name: Upload Binaries
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v5
        with:
          name: readiness-tool
          path: artifacts/

      - name: Publish Release Asset
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path artifacts/* -DestinationPath patina_readiness_tool.zip
          gh release upload ${{ github.event.release.tag_name }} patina_readiness_tool.zip
